### ISSUE TITLE
Avoid using blacklist

### ISSUE THREAD

**Issue by ysangkok** [digfish/pyspotifymuter#1]
Hi, I am happy you are continuing working on this (I was working on the blacklist based approach in Bash on Linux). But why are you still using the blacklist?

There are two ways to block on Linux:
* DBUS based, like in my repo http://github.com/ysangkok/spotify-mute
* LD_PRELOAD based like in https://github.com/abba23/spotify-adblock-linux

Don't you think either of these could be adapted to work on Windows? I guess the Windows equivalent of DBUS is COM. I never understood why they added DBUS support for querying this stuff. So maybe there is a COM interface...

**Comment by digfish** [comment]
Hi, thanks for your remark. Answering directly to your question, yes, I'm still using blacklist because can't find another way. Thanks for your tip, I'll take a look on how it's possible to communicate to a process on Windows using the COM interface. By now, I'm not sure if there is a command tool to manage the COM on windows, or there is a python module able to do that...

**Comment by ysangkok** [comment]
All right, thank you for the response. I'll close this since it is more of a feature suggestion and not an actual bug.
